"""Aportes y alcance de proyectos; estados sin afirmar despliegues no confirmados."""
from project_evidence import DENTAL_PHOTOS

PROJECT_DETAILS = {
    'Sistema UNLi': {
        'purpose': 'Centralizar accesos, asistencia y habilitaciones del laboratorio, con registros para alumnos, docentes y visitantes.',
        'contribution': 'Desarrollé el panel Flask y la aplicación Android con registro QR. Integré bases de datos, importación y exportación de alumnos y flujos de Microsoft 365 para avisos y habilitaciones.',
        'status': 'Desarrollo activo',
        'scope': 'Panel administrativo y aplicación Android. El registro QR y la gestión de habilitaciones forman parte del mismo flujo.',
        'evidence': 'Captura de la interfaz administrativa con datos de demostración. Los valores mostrados son ejemplos; no se publican registros personales ni métricas reales de estudiantes.',
        'links': [],
        'image': ('unli-demostracion.jpg', 'Panel administrativo UNLi con datos de demostración y cuenta de ejemplo.', 'Interfaz real con datos de demostración. No contiene registros personales reales.'),
    },
    'OdontologiaRA': {
        'purpose': 'Explorar modelos anatómicos craneales y odontológicos en realidad mixta para demostraciones y educación.',
        'contribution': 'Desarrollé en Unity/C# la selección de modelos anatómicos, el control de transparencia y la manipulación con una o dos manos. Integré OpenXR, XR Interaction Toolkit y passthrough para explorar los modelos en Meta Quest 3.',
        'status': 'Prototipo de realidad mixta',
        'scope': 'Visualización anatómica y odontológica en Meta Quest 3, combinando modelos digitales con el entorno real. Prototipo para exploración y demostración educativa.',
        'evidence': 'Proyecto Unity con modelos anatómicos, menú de selección, transparencia y controles de manipulación. La experiencia requiere un visor; no tiene una demostración web.',
        'links': [('Explorar Mapa 3D', '/proyectos/#mapa-3d')],
    },
    'Mapa 3D': {
        'purpose': 'Explorar y manipular un modelo tridimensional del terreno USS dentro del entorno real.',
        'contribution': 'Adapté el terreno USS a Unity con versiones para Quest y mayor detalle. Integré selección de modelos, passthrough y controles para mover, girar y escalar el mapa con una o dos manos.',
        'status': 'Prototipo de realidad mixta',
        'scope': 'Modelo de terreno para exploración espacial en Meta Quest con OpenXR y XR Interaction Toolkit. La experiencia requiere un visor y permite seleccionar entre versiones para Quest y mayor detalle.',
        'evidence': 'Proyecto Unity con la escena, los modelos TerrenoUSS_Quest y TerrenoUSS_HQ, y scripts de selección y manipulación con las manos.',
        'links': [('Explorar OdontologiaRA', '/proyectos/#odontologiara')],
    },
    'Integraciones MCP': {
        'purpose': 'Conectar asistentes de IA con herramientas de modelado y desarrollo para ejecutar tareas en el entorno local.',
        'contribution': 'Desarrollé y amplié cuatro integraciones: Inventor mediante COM, Blender mediante Python, Fusion con un bridge autenticado y Unity para editar escenas, componentes y scripts.',
        'status': 'Cuatro integraciones locales',
        'scope': 'Ejemplo de uso: «Inspecciona la pieza abierta en Inventor y expórtala a STL». La integración permite consultar cuerpos y operaciones y exportar el archivo desde el documento.',
        'evidence': 'Herramientas, instrucciones de instalación y ejemplos de uso de las cuatro integraciones locales.',
        'links': [],
        'cover_image': ('mcp-concepto-ia.png', 'Ilustración conceptual de un asistente conectado a cuatro herramientas de ingeniería y desarrollo 3D.', 'Ilustración conceptual generada con IA.'),
    },
    'DJI: visión y telemetría': {
        'purpose': 'Relacionar lo que muestra el video con detecciones de objetos y telemetría para observar y registrar el entorno del dron.',
        'contribution': 'Integré Android/Kotlin con DJI Mobile SDK y un servidor Python para recibir video H.264 y telemetría. Añadí detección YOLO, un panel web y registro de eventos.',
        'status': 'Prototipo de observación',
        'scope': 'Observación pasiva con DJI Mini 3 Pro. La plataforma recibe información; no presenta navegación autónoma ni control de vuelo por IA.',
        'evidence': 'Captura real del panel de video, telemetría y observaciones; la vista mostrada no tiene un dron conectado.',
        'links': [],
        'image': ('dji-panel.jpg', 'Panel de observación DJI esperando una conexión, sin telemetría ni coordenadas reales.', 'Panel de observación en su estado de espera, sin dron conectado.'),
    },
    'Dedos Interactivos': {
        'purpose': 'Explorar las manos como interfaz para controlar efectos visuales en tiempo real.',
        'contribution': 'Desarrollé la detección con MediaPipe, los efectos WebGL2, la selección y el apagado de cámara y la versión de escritorio con Electron. Adapté la experiencia para probarla desde este portafolio.',
        'status': 'Demostración web disponible',
        'scope': 'Cinco modos con instrucciones de pose. El video se procesa en el dispositivo y la cámara se solicita al activarla.',
        'evidence': 'Demostración interactiva disponible sin instalación.',
        'links': [('Abrir laboratorio interactivo', '/dedos-interactivos/')],
        'image': ('dedos-laboratorio.jpg', 'Pantalla real del laboratorio de Dedos Interactivos.', 'Interfaz de la demostración web.'),
    },
    'RoomMapper': {
        'purpose': 'Preparar capturas de una habitación para su reconstrucción 3D posterior.',
        'contribution': 'Desarrollé la captura Android con ARCore, guías de cobertura, filtros de calidad y exportación de fotografías, poses, trayectorias y nubes PLY.',
        'status': 'Prototipo Android',
        'scope': 'La profundidad depende del dispositivo. La app genera un conjunto de datos y una guía geométrica; la reconstrucción densa y el texturizado se realizan después en software especializado.',
        'evidence': 'Captura real de la interfaz de seguimiento y cobertura.',
        'links': [],
        'image': ('roommapper.png', 'Interfaz de RoomMapper con seguimiento AR y guía de cobertura.', 'Captura del prototipo Android; la guía de captura precede a la reconstrucción.'),
    },
    'Lectura de cédula NFC': {
        'purpose': 'Explorar la lectura técnica de cédulas electrónicas chilenas con MRZ y aplicación ICAO eMRTD, con autorización de su titular.',
        'contribution': 'Desarrollé OCR local con ML Kit, acceso BAC e intento PACE cuando el chip lo anuncia, lectura de datos y foto con JMRTD y comprobaciones de hashes y firma interna. Los datos se procesan en memoria.',
        'status': 'Prototipo técnico',
        'scope': 'Requiere Android con NFC y un documento compatible. Compara los datos con EF.SOD; todavía falta validar la cadena de confianza del emisor y completar pruebas entre versiones de cédula. No equivale a identidad verificada.',
        'evidence': 'Vista ilustrativa del menú basada en los textos, colores y distribución del prototipo Android, con campos vacíos. No es una captura de un dispositivo ni una prueba de lectura de un documento.',
        'links': [],
        'cover_image': ('nfc-concepto-ia.png', 'Ilustración conceptual de un teléfono Android leyendo una tarjeta mediante NFC.', 'Ilustración conceptual generada con IA.'),
        'gallery_label': 'Vista del menú · Selecciona la imagen para ampliarla.',
        'gallery': [('nfc-menu-vista-ilustrativa.jpg', 'Vista ilustrativa del menú del prototipo Acceso Cédula NFC, con campos vacíos.', 'Menú recreado a partir del diseño Android del prototipo. Sin datos personales; no es una captura de un dispositivo.')],
    },
    'Biomodelos y simuladores': {
        'purpose': 'Crear recursos físicos y modelos para educación y simulación en salud.',
        'contribution': 'En Odontología digital para el Hospital Félix Bulnes junto a la USS, participé en diseño e impresión de biomodelos y realidad mixta (septiembre-diciembre de 2025, 60 horas). Por separado, diseño piezas, cajas y soportes CAD para simulación obstétrica.',
        'status': 'Prototipado y participación académica',
        'scope': 'Archivos editables en Inventor y exportación STL. El trabajo de odontología digital y el diseño de simuladores obstétricos corresponden a aportes distintos.',
        'evidence': 'Fotografías del modelo digital, la impresión y los biomodelos físicos del proyecto de Odontología digital. Las imágenes se muestran tal como están en el archivo del proyecto.',
        'links': [],
        'gallery': DENTAL_PHOTOS,
    },
    'Juego para admisión USS': {
        'purpose': 'Proponer una actividad demostrativa de interacción y colaboración para admisión USS.',
        'contribution': 'Desarrollé el juego cooperativo en Python/Pygame, los controles por teclado y mando y el empaquetado para Windows.',
        'status': 'Desarrollo para Windows',
        'scope': 'Juego de aviones cooperativo con escenarios de ambientación chilena y un jefe final. Admite teclado y mando para la participación de los jugadores.',
        'evidence': 'Captura de desarrollo del escenario Santiago, con el avión, proyectiles y panel de juego.',
        'links': [],
        'image': ('juego-santiago.png', 'Captura de desarrollo del juego de aviones USS en el escenario Santiago.', 'Captura de desarrollo del escenario Santiago del juego para admisión USS.'),
    },
}
