"""Aportes y alcance de proyectos; estados sin afirmar despliegues no confirmados."""

PROJECT_DETAILS = {
    'Sistema UNLi': {
        'purpose': 'Centralizar accesos, asistencia y habilitaciones del laboratorio, con registros para alumnos, docentes y visitantes.',
        'contribution': 'Desarrollé el panel Flask y la aplicación Android con registro QR. Integré bases de datos, importación y exportación de alumnos y flujos de Microsoft 365 para avisos y habilitaciones.',
        'status': 'Desarrollo activo',
        'scope': 'Panel administrativo y aplicación Android. El registro QR y la gestión de habilitaciones forman parte del mismo flujo.',
        'evidence': 'Código del panel, lector QR y documentación del proyecto.',
        'links': [],
    },
    'PatientAR': {
        'purpose': 'Explorar modelos 3D en realidad mixta para demostraciones y experiencias de salud y educación.',
        'contribution': 'Desarrollé la interacción en Unity/C#: selección, transparencia y manipulación con una o dos manos. Integré OpenXR y XR Interaction Toolkit y herramientas para transmitir la vista del Quest al PC.',
        'status': 'Prototipo de realidad mixta',
        'scope': 'En Meta Quest 3, el passthrough permite ver el entorno real mientras se exploran los modelos digitales. La transmisión al PC facilita las demostraciones.',
        'evidence': 'Funciones desarrolladas: seleccionar un modelo, moverlo con una mano y escalarlo con ambas. La experiencia requiere un visor; no tiene una demostración web.',
        'links': [],
    },
    'Integraciones MCP': {
        'purpose': 'Conectar asistentes de IA con herramientas de modelado y desarrollo para ejecutar tareas en el entorno local.',
        'contribution': 'Desarrollé y amplié cuatro integraciones: Inventor mediante COM, Blender mediante Python, Fusion con un bridge autenticado y Unity para editar escenas, componentes y scripts.',
        'status': 'Cuatro integraciones locales',
        'scope': 'Ejemplo de uso: «Inspecciona la pieza abierta en Inventor y expórtala a STL». La integración permite consultar cuerpos y operaciones y exportar el archivo desde el documento.',
        'evidence': 'Herramientas, instrucciones de instalación y ejemplos de uso de las cuatro integraciones locales.',
        'links': [],
    },
    'DJI: visión y telemetría': {
        'purpose': 'Relacionar lo que muestra el video con detecciones de objetos y telemetría para observar y registrar el entorno del dron.',
        'contribution': 'Integré Android/Kotlin con DJI Mobile SDK y un servidor Python para recibir video H.264 y telemetría. Añadí detección YOLO, un panel web y registro de eventos.',
        'status': 'Prototipo de observación',
        'scope': 'Observación pasiva con DJI Mini 3 Pro. La plataforma recibe información; no presenta navegación autónoma ni control de vuelo por IA.',
        'evidence': 'Aplicación Android, servidor de detección y panel web desarrollados para la integración.',
        'links': [],
    },
    'Dedos Interactivos': {
        'purpose': 'Explorar las manos como interfaz para controlar efectos visuales en tiempo real.',
        'contribution': 'Desarrollé la detección con MediaPipe, los efectos WebGL2, la selección y el apagado de cámara y la versión de escritorio con Electron. Adapté la experiencia para probarla desde este portafolio.',
        'status': 'Demostración web disponible',
        'scope': 'Cinco modos con instrucciones de pose. El video se procesa en el dispositivo y la cámara se solicita al activarla.',
        'evidence': 'Demostración interactiva disponible sin instalación.',
        'links': [('Abrir laboratorio interactivo', '/dedos-interactivos/')],
        'image': ('dedos-laboratorio.jpg', 'Pantalla real del laboratorio de Dedos Interactivos.', 'Interfaz de la demostración web.'),
    },
    'RoomMapper': {
        'purpose': 'Preparar capturas de una habitación para su reconstrucción 3D posterior.',
        'contribution': 'Desarrollé la captura Android con ARCore, guías de cobertura, filtros de calidad y exportación de fotografías, poses, trayectorias y nubes PLY.',
        'status': 'Prototipo Android',
        'scope': 'La profundidad depende del dispositivo. La app genera un conjunto de datos y una guía geométrica; la reconstrucción densa y el texturizado se realizan después en software especializado.',
        'evidence': 'Captura real de la interfaz de seguimiento y cobertura.',
        'links': [],
        'image': ('roommapper.png', 'Interfaz de RoomMapper con seguimiento AR y guía de cobertura.', 'Captura del prototipo Android; la guía de captura precede a la reconstrucción.'),
    },
    'Lectura de cédula NFC': {
        'purpose': 'Explorar la lectura técnica de cédulas electrónicas chilenas con MRZ y aplicación ICAO eMRTD, con autorización de su titular.',
        'contribution': 'Desarrollé OCR local con ML Kit, acceso BAC e intento PACE cuando el chip lo anuncia, lectura de datos y foto con JMRTD y comprobaciones de hashes y firma interna. Los datos se procesan en memoria.',
        'status': 'Prototipo técnico',
        'scope': 'Requiere Android con NFC y un documento compatible. Compara los datos con EF.SOD; todavía falta validar la cadena de confianza del emisor y completar pruebas entre versiones de cédula. No equivale a identidad verificada.',
        'evidence': 'Repositorio con el alcance, requisitos y límites de las comprobaciones implementadas.',
        'links': [],
    },
    'Biomodelos y simuladores': {
        'purpose': 'Crear recursos físicos y modelos para educación y simulación en salud.',
        'contribution': 'En Odontología digital para el Hospital Félix Bulnes junto a la USS, participé en diseño e impresión de biomodelos y realidad mixta (septiembre-diciembre de 2025, 60 horas). Por separado, diseño piezas, cajas y soportes CAD para simulación obstétrica.',
        'status': 'Prototipado y participación académica',
        'scope': 'Archivos editables en Inventor y exportación STL. El trabajo de odontología digital y el diseño de simuladores obstétricos corresponden a aportes distintos.',
        'evidence': 'Modelos CAD editables y archivos STL de los componentes desarrollados.',
        'links': [],
    },
    'Juego para admisión USS': {
        'purpose': 'Proponer una actividad demostrativa de interacción y colaboración para admisión USS.',
        'contribution': 'Desarrollé el juego cooperativo en Python/Pygame, los controles por teclado y mando y el empaquetado para Windows.',
        'status': 'Desarrollo para Windows',
        'scope': 'Participación cooperativa en escenarios de ambientación chilena, con controles por teclado o mando.',
        'evidence': 'Juego empaquetado como ejecutable para actividades demostrativas.',
        'links': [],
    },
}
